version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "6.0"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    network_mode: service:db
    volumes:
       - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: '5480'

volumes:
  postgres-data:
  pgadmin: